name: analyst

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # dependencies
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Go environment
        uses: actions/setup-go@v2-beta

      # effective action
      - name: Run latest packages build
        run: |
          go test ./...